name: Auto Update IPTV List

on:
  schedule:
    # 每小時執行一次 (UTC 時間，0 分時觸發)
    - cron: '0 * * * *'
  workflow_dispatch:
    # 允許手動點擊按鈕執行測試

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python update_iptv.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # 檢查是否有檔案變動，有的話才提交
          git add 4gtv.m3u smart.m3u
          git commit -m "Auto updated m3u files at $(date)" || echo "No changes to commit"
          git push
