name: Auto Update IPTV List

on:
  schedule:
    # 每兩小時執行一次 (UTC 時間，0, 2, 4... 以此類推)
    - cron: '0 */2 * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_iptv.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update: $(date)" && git push)

